# files
file1=No_14
file2=No_15
file3=No_19
file4=No_20
file5=No_28
file6=No_31

# srcfile=$(file1).cpp $(file2).cpp $(file3).cpp $(file4).cpp
# tgtfile=$(srcfile:.cpp=.out)

# compile
FLAG +=
g11  = g++-4.8 -std=c++11 -Wall -m64 -msse -msse2

all:
	$(g11) $(FLAG) -o $(file1).out $(file1).cpp
	$(g11) $(FLAG) -o $(file2).out $(file2).cpp
	$(g11) $(FLAG) -o $(file3).out $(file3).cpp
	$(g11) $(FLAG) -o $(file4).out $(file4).cpp
	$(g11) $(FLAG) -o $(file5).out $(file5).cpp
	$(g11) $(FLAG) -o $(file6).out $(file6).cpp

clean:
	rm *.out

