STACKS SEGMENT
    ARR DW 10 DUP(1,2,3,4,5,6,7,8,9,0)
    ARR_P DW ?
STACKS ENDS

CODES SEGMENT
    ASSUME CS:CODES,SS:STACKS
START:
    ;INIT
    MOV AX,STACKS
    MOV SS,AX
    MOV AX,ARR_P
    MOV SP,AX
    ;Addition
    POP AX
    MOV CX,9
ADDITION:
    POP BX
    ADD AX,BX
    DEC CX
    JNZ ADDITION
	;EXIT_SUCCESS
    MOV AH,4CH
    INT 21H
CODES ENDS
    END START
