SET(__FLENS_DIR__ "${CMAKE_CURRENT_LIST_DIR}/../FLENS")
MARK_AS_ADVANCED(__FLENS_DIR__)

SET(CMAKE_CXX_COMPILER g++-4.8)
SET(CMAKE_CXX_FLAGS "-std=c++11 -m64 -msse -msse2 -march=native -O3 ${CMAKE_CXX_FLAGS}")

MESSAGE(STATUS "C++ Compiler: ${CMAKE_CXX_COMPILER}")
MESSAGE(STATUS "C++ FLAGS: ${CMAKE_CXX_FLAGS}")
MESSAGE(STATUS "C++ FLAGS Debug: ${CMAKE_CXX_FLAGS_DEBUG}")
MESSAGE(STATUS "C++ FLAGS Release: ${CMAKE_CXX_FLAGS_RELEASE}")

INCLUDE_DIRECTORIES("/opt/boost_1_54_0/include/")
LINK_DIRECTORIES("/opt/boost_1_54_0/lib/")

INCLUDE_DIRECTORIES(${__FLENS_DIR__})

