all:
	g++ -o ./leave-a-message-form.cgi ./leave-a-message-form.cpp -lsqlite3 `pkg-config --libs --cflags fastcgi++`
	g++ -o ./show-all-message.cgi ./show-all-message.cpp -lsqlite3 `pkg-config --libs --cflags fastcgi++`

